// @generated by Stage 6 migration: comparison unit tests moved from the
// application layer into the recovery feature package.
package recovery

import (
	"testing"

	"github.com/waxlight/waxlight-launcher/internal/snapshots"
)

func TestCompareConfigurations(t *testing.T) {
	lkg := LastKnownGood{
		GameVersion: "1.20",
		Mods: []snapshots.Mod{
			{Source: snapshots.ModSourceModDB, ModID: "A", ReleaseID: "r1", Version: "1.0.0"},
			{Source: snapshots.ModSourceModDB, ModID: "B", ReleaseID: "r2", Version: "2.0.0"},
			{Source: snapshots.ModSourceModDB, ModID: "C", ReleaseID: "r3", Version: "3.0.0"},
		},
	}
	current := []snapshots.Mod{
		{Source: snapshots.ModSourceModDB, ModID: "A", ReleaseID: "r4", Version: "2.0.0"},
		{Source: snapshots.ModSourceModDB, ModID: "B", ReleaseID: "r2", Version: "2.0.0"},
		{Source: snapshots.ModSourceModDB, ModID: "D", ReleaseID: "r5", Version: "1.0.0"},
	}
	names := map[string]string{
		"moddb:A": "Alpha",
		"moddb:B": "Beta",
		"moddb:D": "Delta",
	}

	changes := compareConfigurations(lkg, current, names, "1.20")
	if len(changes.Updated) != 1 || changes.Updated[0].Name != "Alpha" ||
		changes.Updated[0].From != "1.0.0" || changes.Updated[0].To != "2.0.0" {
		t.Fatalf("unexpected updated mods: %#v", changes.Updated)
	}
	if len(changes.Added) != 1 || changes.Added[0].Name != "Delta" || changes.Added[0].To != "1.0.0" {
		t.Fatalf("unexpected added mods: %#v", changes.Added)
	}
	if len(changes.Removed) != 1 || changes.Removed[0].Name != "C" || changes.Removed[0].From != "3.0.0" {
		t.Fatalf("unexpected removed mods: %#v", changes.Removed)
	}
	if changes.GameVersionFrom != "" {
		t.Fatalf("unexpected game version change: %#v", changes)
	}
	if changes.Count() != 3 {
		t.Fatalf("expected 3 changes, got %d", changes.Count())
	}
	if changes.Empty() {
		t.Fatal("changes must not be empty")
	}
}

func TestGameVersionChangeDetection(t *testing.T) {
	lkg := LastKnownGood{GameVersion: "1.21.5"}
	changes := compareConfigurations(lkg, nil, nil, "1.21.6")
	if changes.GameVersionFrom != "1.21.5" || changes.GameVersionTo != "1.21.6" {
		t.Fatalf("unexpected game version change: %#v", changes)
	}
	if changes.Count() != 1 {
		t.Fatalf("expected 1 change, got %d", changes.Count())
	}
	unchanged := compareConfigurations(lkg, nil, nil, "1.21.5")
	if !unchanged.Empty() {
		t.Fatalf("same game version must not be a change: %#v", unchanged)
	}
}
