package telemetry

import (
	"context"
	"log/slog"

	"github.com/google/uuid"
)

// installationIDKey is the app_settings key that stores the random
// installation UUID. It is deliberately a plain settings entry, not a
// credential, and never enters the native keyring.
const installationIDKey = "telemetry_installation_id"

// KVStore persists small telemetry state values inside the normal Waxlight
// settings storage.
type KVStore interface {
	GetSettingValue(context.Context, string) (string, error)
	SetSettingValue(context.Context, string, string) error
}

// identity owns the persistent random installation UUID.
//
// The UUID is generated once with a cryptographically secure random source
// (crypto/rand via google/uuid), persists across restarts, and is not derived
// from hardware, the operating system, the user name, or filesystem paths. It
// is pseudonymous, not a secret, and is never regenerated by toggling
// telemetry on or off.
type identity struct {
	store KVStore
}

func newIdentity(store KVStore) *identity {
	return &identity{store: store}
}

// ID returns the installation UUID, creating and persisting it on first use.
// A zero or malformed stored value is replaced with a fresh UUID.
func (id *identity) ID(ctx context.Context) string {
	existing, err := id.store.GetSettingValue(ctx, installationIDKey)
	if err == nil && uuid.Validate(existing) == nil {
		return existing
	}
	generated, err := uuid.NewRandom()
	if err != nil {
		slog.Warn("telemetry: could not generate installation ID", "error", err)
		return ""
	}
	value := generated.String()
	if err := id.store.SetSettingValue(ctx, installationIDKey, value); err != nil {
		slog.Warn("telemetry: could not persist installation ID", "error", err)
		return value
	}
	slog.Debug("telemetry: installation ID created")
	return value
}
