// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelLogin(arg1) {
  return window['go']['presentation']['AccountController']['CancelLogin'](arg1);
}

export function CompleteTOTP(arg1, arg2) {
  return window['go']['presentation']['AccountController']['CompleteTOTP'](arg1, arg2);
}

export function ListAccounts() {
  return window['go']['presentation']['AccountController']['ListAccounts']();
}

export function Login(arg1, arg2) {
  return window['go']['presentation']['AccountController']['Login'](arg1, arg2);
}

export function ReauthenticateAccount(arg1, arg2, arg3) {
  return window['go']['presentation']['AccountController']['ReauthenticateAccount'](arg1, arg2, arg3);
}

export function RemoveAccount(arg1) {
  return window['go']['presentation']['AccountController']['RemoveAccount'](arg1);
}

export function SetDefaultAccount(arg1) {
  return window['go']['presentation']['AccountController']['SetDefaultAccount'](arg1);
}

export function ValidateAccount(arg1) {
  return window['go']['presentation']['AccountController']['ValidateAccount'](arg1);
}
