// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presentation} from '../models';

export function InstallLocalVersion(arg1:presentation.InstallVersionRequest):Promise<presentation.OperationDTO>;

export function ListInstalledVersions():Promise<Array<presentation.GameVersionDTO>>;

export function RemoveVersion(arg1:string,arg2:boolean):Promise<void>;
