// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallLocalVersion(arg1) {
  return window['go']['presentation']['GameVersionController']['InstallLocalVersion'](arg1);
}

export function InstallVersion(arg1) {
  return window['go']['presentation']['GameVersionController']['InstallVersion'](arg1);
}

export function ListAvailableVersions() {
  return window['go']['presentation']['GameVersionController']['ListAvailableVersions']();
}

export function ListInstalledVersions() {
  return window['go']['presentation']['GameVersionController']['ListInstalledVersions']();
}

export function RemoveVersion(arg1, arg2) {
  return window['go']['presentation']['GameVersionController']['RemoveVersion'](arg1, arg2);
}
