// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presentation} from '../models';

export function ExportInstance(arg1:presentation.ExportInstanceRequest):Promise<presentation.PackageManifestDTO>;

export function ImportPackage(arg1:presentation.ImportInstanceRequest):Promise<presentation.ImportReportDTO>;

export function InspectPackage(arg1:string):Promise<presentation.PackageInspectionDTO>;

export function SelectExportPath(arg1:string):Promise<string>;

export function SelectPackageFile():Promise<string>;
