// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presentation} from '../models';

export function CreateInstance(arg1:presentation.CreateInstanceRequest):Promise<presentation.InstanceDTO>;

export function DeleteInstance(arg1:string,arg2:boolean):Promise<void>;

export function GetInstance(arg1:string):Promise<presentation.InstanceDTO>;

export function ListInstances():Promise<Array<presentation.InstanceDTO>>;

export function UpdateInstance(arg1:presentation.UpdateInstanceRequest):Promise<presentation.InstanceDTO>;
