// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportInstance(arg1) {
  return window['go']['presentation']['InstancePackageController']['ExportInstance'](arg1);
}

export function ImportPackage(arg1) {
  return window['go']['presentation']['InstancePackageController']['ImportPackage'](arg1);
}

export function InspectPackage(arg1) {
  return window['go']['presentation']['InstancePackageController']['InspectPackage'](arg1);
}

export function SelectExportPath(arg1) {
  return window['go']['presentation']['InstancePackageController']['SelectExportPath'](arg1);
}

export function SelectPackageFile() {
  return window['go']['presentation']['InstancePackageController']['SelectPackageFile']();
}
