// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateInstance(arg1) {
  return window['go']['presentation']['InstanceController']['CreateInstance'](arg1);
}

export function DeleteInstance(arg1, arg2) {
  return window['go']['presentation']['InstanceController']['DeleteInstance'](arg1, arg2);
}

export function GetInstance(arg1) {
  return window['go']['presentation']['InstanceController']['GetInstance'](arg1);
}

export function ListInstances() {
  return window['go']['presentation']['InstanceController']['ListInstances']();
}

export function UpdateInstance(arg1) {
  return window['go']['presentation']['InstanceController']['UpdateInstance'](arg1);
}
