// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInstanceLastKnownGood(arg1) {
  return window['go']['presentation']['LastKnownGoodController']['GetInstanceLastKnownGood'](arg1);
}
