// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presentation} from '../models';

export function GetInstanceLastKnownGood(arg1:string):Promise<presentation.LastKnownGoodDTO>;
