// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presentation} from '../models';

export function CheckUpdates(arg1:string):Promise<presentation.LauncherUpdateDTO>;

export function CurrentVersion():Promise<string>;

export function InstallUpdate(arg1:string):Promise<void>;

export function OpenReleasePage(arg1:string):Promise<void>;
