// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presentation} from '../models';

export function ForceStopInstance(arg1:string):Promise<void>;

export function GetRunningInstances():Promise<Array<string>>;

export function LaunchInstance(arg1:presentation.LaunchRequest):Promise<presentation.PlaySessionDTO>;

export function LaunchServer(arg1:presentation.ServerLaunchRequest):Promise<presentation.PlaySessionDTO>;

export function StopInstance(arg1:string):Promise<void>;

export function ValidateLaunch(arg1:presentation.LaunchRequest):Promise<presentation.LaunchValidationDTO>;
