// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportLogs():Promise<string>;

export function ListLogs(arg1:number):Promise<Array<string>>;

export function OpenLogsDirectory():Promise<void>;

export function WriteLog(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;
