// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportLogs() {
  return window['go']['presentation']['LogController']['ExportLogs']();
}

export function ListLogs(arg1) {
  return window['go']['presentation']['LogController']['ListLogs'](arg1);
}

export function OpenLogsDirectory() {
  return window['go']['presentation']['LogController']['OpenLogsDirectory']();
}

export function WriteLog(arg1, arg2, arg3) {
  return window['go']['presentation']['LogController']['WriteLog'](arg1, arg2, arg3);
}
