// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presentation} from '../models';

export function CancelModTask(arg1:string):Promise<void>;

export function CheckModUpdates(arg1:string):Promise<Array<presentation.DownloadedModDTO>>;

export function DownloadMod(arg1:presentation.DownloadCatalogModRequest):Promise<presentation.ModInstallResultDTO>;

export function GetMod(arg1:string):Promise<presentation.ModDetailsDTO>;

export function InstallDownloadedMod(arg1:presentation.InstallDownloadedModRequest):Promise<presentation.ModInstallResultDTO>;

export function ListDownloadedMods():Promise<Array<presentation.DownloadedModDTO>>;

export function ListModTags():Promise<Array<presentation.ModTagDTO>>;

export function RemoveDownloadedMod(arg1:string,arg2:string):Promise<void>;

export function SearchMods(arg1:presentation.ModSearchRequest):Promise<presentation.ModSearchResultDTO>;

export function UploadMods(arg1:Array<string>):Promise<presentation.UploadModsResultDTO>;
