// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelModTask(arg1) {
  return window['go']['presentation']['ModCatalogController']['CancelModTask'](arg1);
}

export function CheckModUpdates(arg1) {
  return window['go']['presentation']['ModCatalogController']['CheckModUpdates'](arg1);
}

export function DownloadMod(arg1) {
  return window['go']['presentation']['ModCatalogController']['DownloadMod'](arg1);
}

export function GetMod(arg1) {
  return window['go']['presentation']['ModCatalogController']['GetMod'](arg1);
}

export function InstallDownloadedMod(arg1) {
  return window['go']['presentation']['ModCatalogController']['InstallDownloadedMod'](arg1);
}

export function ListDownloadedMods() {
  return window['go']['presentation']['ModCatalogController']['ListDownloadedMods']();
}

export function ListModTags() {
  return window['go']['presentation']['ModCatalogController']['ListModTags']();
}

export function RemoveDownloadedMod(arg1, arg2) {
  return window['go']['presentation']['ModCatalogController']['RemoveDownloadedMod'](arg1, arg2);
}

export function SearchMods(arg1) {
  return window['go']['presentation']['ModCatalogController']['SearchMods'](arg1);
}

export function UploadMods(arg1) {
  return window['go']['presentation']['ModCatalogController']['UploadMods'](arg1);
}
