// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presentation} from '../models';

export function CheckInstanceModUpdates(arg1:string):Promise<presentation.InstanceModUpdateReportDTO>;

export function InstallModFile(arg1:presentation.InstallModFileRequest):Promise<presentation.OperationDTO>;

export function InstallModFiles(arg1:presentation.InstallModFilesRequest):Promise<presentation.InstallModFilesResultDTO>;

export function ListInstalledMods(arg1:string):Promise<Array<presentation.InstalledModDTO>>;

export function RemoveMod(arg1:string):Promise<void>;

export function SetModEnabled(arg1:string,arg2:boolean):Promise<presentation.InstalledModDTO>;
