// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallModFile(arg1) {
  return window['go']['presentation']['ModManagerController']['InstallModFile'](arg1);
}

export function ListInstalledMods(arg1) {
  return window['go']['presentation']['ModManagerController']['ListInstalledMods'](arg1);
}

export function RemoveMod(arg1) {
  return window['go']['presentation']['ModManagerController']['RemoveMod'](arg1);
}

export function SetModEnabled(arg1, arg2) {
  return window['go']['presentation']['ModManagerController']['SetModEnabled'](arg1, arg2);
}
