// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presentation} from '../models';

export function CheckInstanceModUpdates(arg1:string):Promise<presentation.InstanceModUpdateReportDTO>;

export function GetModDeletePreview(arg1:string):Promise<presentation.ModDeletePreviewDTO>;

export function InstallModFile(arg1:presentation.InstallModFileRequest):Promise<presentation.OperationDTO>;

export function InstallModFiles(arg1:presentation.InstallModFilesRequest):Promise<presentation.InstallModFilesResultDTO>;

export function LinkLocalMods(arg1:string):Promise<presentation.LinkLocalModsResultDTO>;

export function ListInstalledMods(arg1:string):Promise<Array<presentation.InstalledModDTO>>;

export function RemoveMod(arg1:string,arg2:boolean):Promise<void>;

export function SetModEnabled(arg1:string,arg2:boolean):Promise<presentation.InstalledModDTO>;

export function UpdateInstanceMods(arg1:presentation.UpdateInstanceModsRequest):Promise<presentation.ModUpdateResultDTO>;
