// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelOperation(arg1) {
  return window["go"]["presentation"]["OperationController"]["CancelOperation"](arg1);
}

export function ClearOperationHistory() {
  return window["go"]["presentation"]["OperationController"]["ClearOperationHistory"]();
}

export function DeleteOperation(arg1) {
  return window["go"]["presentation"]["OperationController"]["DeleteOperation"](arg1);
}

export function ListOperations() {
  return window["go"]["presentation"]["OperationController"]["ListOperations"]();
}
