// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presentation} from '../models';

export function DeleteFavoriteServer(arg1:string):Promise<void>;

export function ListFavoriteServers():Promise<Array<presentation.FavoriteServerDTO>>;

export function ListPublicServers():Promise<Array<presentation.PublicServerDTO>>;

export function SaveFavoriteServer(arg1:presentation.SaveFavoriteServerRequest):Promise<presentation.FavoriteServerDTO>;
