// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFavoriteServer(arg1) {
  return window['go']['presentation']['ServerController']['DeleteFavoriteServer'](arg1);
}

export function ListFavoriteServers() {
  return window['go']['presentation']['ServerController']['ListFavoriteServers']();
}

export function ListPublicServers() {
  return window['go']['presentation']['ServerController']['ListPublicServers']();
}

export function SaveFavoriteServer(arg1) {
  return window['go']['presentation']['ServerController']['SaveFavoriteServer'](arg1);
}
