// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presentation} from '../models';

export function GetSettings():Promise<presentation.SettingsDTO>;

export function OpenDirectory(arg1:string):Promise<void>;

export function SelectGameArchive():Promise<string>;

export function SelectGameDirectory():Promise<string>;

export function SelectModFile():Promise<string>;

export function UpdateSettings(arg1:presentation.SettingsDTO):Promise<presentation.SettingsDTO>;
