// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataFolder() {
  return window['go']['presentation']['SettingsController']['GetDataFolder']();
}

export function GetSettings() {
  return window['go']['presentation']['SettingsController']['GetSettings']();
}

export function MoveDataFolder(arg1) {
  return window['go']['presentation']['SettingsController']['MoveDataFolder'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['presentation']['SettingsController']['OpenDirectory'](arg1);
}

export function SelectDataFolder() {
  return window['go']['presentation']['SettingsController']['SelectDataFolder']();
}

export function SelectGameArchive() {
  return window['go']['presentation']['SettingsController']['SelectGameArchive']();
}

export function SelectGameDirectory() {
  return window['go']['presentation']['SettingsController']['SelectGameDirectory']();
}

export function SelectModFile() {
  return window['go']['presentation']['SettingsController']['SelectModFile']();
}

export function UpdateSettings(arg1) {
  return window['go']['presentation']['SettingsController']['UpdateSettings'](arg1);
}
