// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateInstanceSnapshot(arg1) {
  return window['go']['presentation']['SnapshotController']['CreateInstanceSnapshot'](arg1);
}

export function DeleteInstanceSnapshot(arg1, arg2) {
  return window['go']['presentation']['SnapshotController']['DeleteInstanceSnapshot'](arg1, arg2);
}

export function ListInstanceSnapshots(arg1) {
  return window['go']['presentation']['SnapshotController']['ListInstanceSnapshots'](arg1);
}

export function RestoreInstanceSnapshot(arg1, arg2) {
  return window['go']['presentation']['SnapshotController']['RestoreInstanceSnapshot'](arg1, arg2);
}
