// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CancelLogin(arg1:string):Promise<void>;

export function CompleteTOTP(arg1:string,arg2:string):Promise<wails.LoginResultDTO>;

export function ListAccounts():Promise<Array<wails.AccountDTO>>;

export function Login(arg1:string,arg2:string):Promise<wails.LoginResultDTO>;

export function ReauthenticateAccount(arg1:string,arg2:string,arg3:string):Promise<wails.LoginResultDTO>;

export function RemoveAccount(arg1:string):Promise<void>;

export function SetDefaultAccount(arg1:string):Promise<void>;

export function ValidateAccount(arg1:string):Promise<wails.AccountDTO>;
