// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {deeplink} from '../models';

export function ConsumePendingDeepLinks():Promise<Array<deeplink.Target>>;
