// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function InstallLocalVersion(arg1:wails.InstallVersionRequest):Promise<wails.OperationDTO>;

export function InstallVersion(arg1:string):Promise<wails.OperationDTO>;

export function ListAvailableVersions():Promise<Array<wails.AvailableGameVersionDTO>>;

export function ListInstalledVersions():Promise<Array<wails.GameVersionDTO>>;

export function RemoveVersion(arg1:string,arg2:boolean):Promise<void>;
