// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function ExportInstance(arg1:wails.ExportInstanceRequest):Promise<wails.PackageManifestDTO>;

export function ImportPackage(arg1:wails.ImportInstanceRequest):Promise<wails.ImportReportDTO>;

export function InspectPackage(arg1:string):Promise<wails.PackageInspectionDTO>;

export function SelectExportPath(arg1:string):Promise<string>;

export function SelectPackageFile():Promise<string>;
