// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CloneInstance(arg1:wails.CloneInstanceRequest):Promise<wails.InstanceDTO>;

export function CreateInstance(arg1:wails.CreateInstanceRequest):Promise<wails.InstanceDTO>;

export function DeleteInstance(arg1:string,arg2:boolean):Promise<void>;

export function GetInstance(arg1:string):Promise<wails.InstanceDTO>;

export function ListInstances():Promise<Array<wails.InstanceDTO>>;

export function UpdateInstance(arg1:wails.UpdateInstanceRequest):Promise<wails.InstanceDTO>;
