// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloneInstance(arg1) {
  return window['go']['wails']['InstanceController']['CloneInstance'](arg1);
}

export function CreateInstance(arg1) {
  return window['go']['wails']['InstanceController']['CreateInstance'](arg1);
}

export function DeleteInstance(arg1, arg2) {
  return window['go']['wails']['InstanceController']['DeleteInstance'](arg1, arg2);
}

export function DetectExistingVintageStoryData() {
  return window['go']['wails']['InstanceController']['DetectExistingVintageStoryData']();
}

export function GetInstance(arg1) {
  return window['go']['wails']['InstanceController']['GetInstance'](arg1);
}

export function InspectExistingVintageStoryData(arg1) {
  return window['go']['wails']['InstanceController']['InspectExistingVintageStoryData'](arg1);
}

export function ListInstances() {
  return window['go']['wails']['InstanceController']['ListInstances']();
}

export function SelectInstanceCover() {
  return window['go']['wails']['InstanceController']['SelectInstanceCover']();
}

export function SetInstancePinned(arg1, arg2) {
  return window['go']['wails']['InstanceController']['SetInstancePinned'](arg1, arg2);
}

export function StartExistingDataImport(arg1) {
  return window['go']['wails']['InstanceController']['StartExistingDataImport'](arg1);
}

export function UpdateInstance(arg1) {
  return window['go']['wails']['InstanceController']['UpdateInstance'](arg1);
}
