// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForceStopInstance(arg1) {
  return window['go']['wails']['LaunchController']['ForceStopInstance'](arg1);
}

export function GetRunningInstances() {
  return window['go']['wails']['LaunchController']['GetRunningInstances']();
}

export function LaunchInstance(arg1) {
  return window['go']['wails']['LaunchController']['LaunchInstance'](arg1);
}

export function LaunchServer(arg1) {
  return window['go']['wails']['LaunchController']['LaunchServer'](arg1);
}

export function StopInstance(arg1) {
  return window['go']['wails']['LaunchController']['StopInstance'](arg1);
}

export function ValidateLaunch(arg1) {
  return window['go']['wails']['LaunchController']['ValidateLaunch'](arg1);
}
