// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdates(arg1) {
  return window['go']['wails']['LauncherUpdateController']['CheckUpdates'](arg1);
}

export function CurrentVersion() {
  return window['go']['wails']['LauncherUpdateController']['CurrentVersion']();
}

export function InstallUpdate(arg1) {
  return window['go']['wails']['LauncherUpdateController']['InstallUpdate'](arg1);
}

export function OpenReleasePage(arg1) {
  return window['go']['wails']['LauncherUpdateController']['OpenReleasePage'](arg1);
}

export function OpenUrl(arg1) {
  return window['go']['wails']['LauncherUpdateController']['OpenUrl'](arg1);
}
