// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelModTask(arg1) {
  return window['go']['wails']['ModCatalogController']['CancelModTask'](arg1);
}

export function CheckModUpdates(arg1) {
  return window['go']['wails']['ModCatalogController']['CheckModUpdates'](arg1);
}

export function DownloadMod(arg1) {
  return window['go']['wails']['ModCatalogController']['DownloadMod'](arg1);
}

export function DownloadModsBatch(arg1) {
  return window['go']['wails']['ModCatalogController']['DownloadModsBatch'](arg1);
}

export function GetMod(arg1) {
  return window['go']['wails']['ModCatalogController']['GetMod'](arg1);
}

export function InstallDownloadedMod(arg1) {
  return window['go']['wails']['ModCatalogController']['InstallDownloadedMod'](arg1);
}

export function ListDownloadedMods() {
  return window['go']['wails']['ModCatalogController']['ListDownloadedMods']();
}

export function ListModTags() {
  return window['go']['wails']['ModCatalogController']['ListModTags']();
}

export function PreviewUnusedDownloadedMods() {
  return window['go']['wails']['ModCatalogController']['PreviewUnusedDownloadedMods']();
}

export function RemoveDownloadedMod(arg1, arg2) {
  return window['go']['wails']['ModCatalogController']['RemoveDownloadedMod'](arg1, arg2);
}

export function RemoveUnusedDownloadedMods() {
  return window['go']['wails']['ModCatalogController']['RemoveUnusedDownloadedMods']();
}

export function SearchMods(arg1) {
  return window['go']['wails']['ModCatalogController']['SearchMods'](arg1);
}

export function UploadMods(arg1) {
  return window['go']['wails']['ModCatalogController']['UploadMods'](arg1);
}
