// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CancelModTask(arg1:string):Promise<void>;

export function CheckModUpdates(arg1:string):Promise<Array<wails.DownloadedModDTO>>;

export function DownloadMod(arg1:wails.DownloadCatalogModRequest):Promise<wails.ModInstallResultDTO>;

export function DownloadModsBatch(arg1:wails.DownloadModsBatchRequest):Promise<Array<wails.BatchModInstallResultDTO>>;

export function GetMod(arg1:string):Promise<wails.ModDetailsDTO>;

export function InstallDownloadedMod(arg1:wails.InstallDownloadedModRequest):Promise<wails.ModInstallResultDTO>;

export function ListDownloadedMods():Promise<Array<wails.DownloadedModDTO>>;

export function ListFavoriteModIDs():Promise<Array<string>>;

export function ListFavoriteMods():Promise<Array<wails.ModSummaryDTO>>;

export function ListModTags():Promise<Array<wails.ModTagDTO>>;

export function PreviewUnusedDownloadedMods():Promise<wails.DownloadedModCleanupResultDTO>;

export function RemoveDownloadedMod(arg1:string,arg2:string):Promise<void>;

export function RemoveUnusedDownloadedMods():Promise<wails.DownloadedModCleanupResultDTO>;

export function SearchMods(arg1:wails.ModSearchRequest):Promise<wails.ModSearchResultDTO>;

export function SetModFavorite(arg1:string,arg2:boolean):Promise<void>;

export function UploadMods(arg1:Array<string>):Promise<wails.UploadModsResultDTO>;
