// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CheckInstanceModUpdates(arg1:string):Promise<wails.InstanceModUpdateReportDTO>;

export function GetModDeletePreview(arg1:string):Promise<wails.ModDeletePreviewDTO>;

export function InstallModFile(arg1:wails.InstallModFileRequest):Promise<wails.OperationDTO>;

export function InstallModFiles(arg1:wails.InstallModFilesRequest):Promise<wails.InstallModFilesResultDTO>;

export function LinkLocalMods(arg1:string):Promise<wails.LinkLocalModsResultDTO>;

export function ListInstalledMods(arg1:string):Promise<Array<wails.InstalledModDTO>>;

export function RemoveMod(arg1:string,arg2:boolean):Promise<void>;

export function SetModEnabled(arg1:string,arg2:boolean):Promise<wails.InstalledModDTO>;

export function UpdateInstanceMods(arg1:wails.UpdateInstanceModsRequest):Promise<wails.ModUpdateResultDTO>;
