// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckInstanceModUpdates(arg1) {
  return window['go']['wails']['ModManagerController']['CheckInstanceModUpdates'](arg1);
}

export function GetModDeletePreview(arg1) {
  return window['go']['wails']['ModManagerController']['GetModDeletePreview'](arg1);
}

export function InstallModFile(arg1) {
  return window['go']['wails']['ModManagerController']['InstallModFile'](arg1);
}

export function InstallModFiles(arg1) {
  return window['go']['wails']['ModManagerController']['InstallModFiles'](arg1);
}

export function LinkLocalMods(arg1) {
  return window['go']['wails']['ModManagerController']['LinkLocalMods'](arg1);
}

export function ListInstalledMods(arg1) {
  return window['go']['wails']['ModManagerController']['ListInstalledMods'](arg1);
}

export function RemoveMod(arg1, arg2) {
  return window['go']['wails']['ModManagerController']['RemoveMod'](arg1, arg2);
}

export function SetModEnabled(arg1, arg2) {
  return window['go']['wails']['ModManagerController']['SetModEnabled'](arg1, arg2);
}

export function SetModUpdatePolicy(arg1, arg2) {
  return window['go']['wails']['ModManagerController']['SetModUpdatePolicy'](arg1, arg2);
}

export function UpdateInstanceMods(arg1) {
  return window['go']['wails']['ModManagerController']['UpdateInstanceMods'](arg1);
}
