// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MarkSeen(arg1) {
  return window['go']['wails']['NewsController']['MarkSeen'](arg1);
}

export function OpenArticle(arg1) {
  return window['go']['wails']['NewsController']['OpenArticle'](arg1);
}

export function Sync(arg1) {
  return window['go']['wails']['NewsController']['Sync'](arg1);
}
