// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function MarkSeen(arg1:Array<string>):Promise<void>;

export function OpenArticle(arg1:string):Promise<void>;

export function Sync(arg1:boolean):Promise<wails.NewsFeedDTO>;
