// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelOperation(arg1) {
  return window['go']['wails']['OperationController']['CancelOperation'](arg1);
}

export function ClearOperationHistory() {
  return window['go']['wails']['OperationController']['ClearOperationHistory']();
}

export function DeleteOperation(arg1) {
  return window['go']['wails']['OperationController']['DeleteOperation'](arg1);
}

export function ListOperations() {
  return window['go']['wails']['OperationController']['ListOperations']();
}
