// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CancelOperation(arg1:string):Promise<void>;

export function ClearOperationHistory():Promise<number>;

export function DeleteOperation(arg1:string):Promise<void>;

export function ListOperations():Promise<Array<wails.OperationDTO>>;
