// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['wails']['PresenceController']['Connect']();
}

export function SetEnabled(arg1) {
  return window['go']['wails']['PresenceController']['SetEnabled'](arg1);
}
