// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function DeleteFavoriteServer(arg1:string):Promise<void>;

export function ListFavoriteServers():Promise<Array<wails.FavoriteServerDTO>>;

export function ListPublicServers():Promise<Array<wails.PublicServerDTO>>;

export function SaveFavoriteServer(arg1:wails.SaveFavoriteServerRequest):Promise<wails.FavoriteServerDTO>;
