// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataFolder() {
  return window['go']['wails']['SettingsController']['GetDataFolder']();
}

export function GetSettings() {
  return window['go']['wails']['SettingsController']['GetSettings']();
}

export function MoveDataFolder(arg1) {
  return window['go']['wails']['SettingsController']['MoveDataFolder'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['wails']['SettingsController']['OpenDirectory'](arg1);
}

export function SelectDataFolder() {
  return window['go']['wails']['SettingsController']['SelectDataFolder']();
}

export function SelectGameArchive() {
  return window['go']['wails']['SettingsController']['SelectGameArchive']();
}

export function SelectGameDirectory() {
  return window['go']['wails']['SettingsController']['SelectGameDirectory']();
}

export function SelectModFile() {
  return window['go']['wails']['SettingsController']['SelectModFile']();
}

export function SelectModFiles() {
  return window['go']['wails']['SettingsController']['SelectModFiles']();
}

export function UpdateSettings(arg1) {
  return window['go']['wails']['SettingsController']['UpdateSettings'](arg1);
}
