// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function DetectOptimum():Promise<wails.OptimumStatusDTO>;

export function GetDataFolder():Promise<wails.DataFolderDTO>;

export function GetOptimumStatus():Promise<wails.OptimumStatusDTO>;

export function GetSettings():Promise<wails.SettingsDTO>;

export function InspectOptimum(arg1:string):Promise<wails.OptimumStatusDTO>;

export function MoveDataFolder(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenOptimumInstallationGuide():Promise<void>;

export function SelectDataFolder():Promise<string>;

export function SelectGameArchive():Promise<string>;

export function SelectGameDirectory():Promise<string>;

export function SelectModFile():Promise<string>;

export function SelectModFiles():Promise<Array<string>>;

export function SelectOptimumInstallation():Promise<string>;

export function UpdateSettings(arg1:wails.SettingsDTO):Promise<wails.SettingsDTO>;
