// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CreateInstanceSnapshot(arg1:string):Promise<wails.OperationDTO>;

export function DeleteInstanceSnapshot(arg1:string,arg2:string):Promise<void>;

export function ListInstanceSnapshots(arg1:string):Promise<Array<wails.InstanceSnapshotDTO>>;

export function RestoreInstanceSnapshot(arg1:string,arg2:string):Promise<void>;
