// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {supportreports} from '../models';

export function Preview(arg1:string,arg2:string):Promise<supportreports.Preview>;

export function Submit(arg1:string):Promise<supportreports.Result>;
