// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Preview(arg1, arg2) {
  return window['go']['wails']['SupportReportController']['Preview'](arg1, arg2);
}

export function Submit(arg1) {
  return window['go']['wails']['SupportReportController']['Submit'](arg1);
}
